July 2nd Week
JavaScript101study/JsStudy pull request #38
Opened 2021-07-08 14:52 UTC by brad-go

도저히 compare & pull request 버튼이 왜 안뜨는지,,, 
commit이 n개 앞에 있다는 소리는 왜 여러 방법을 써도 안없어지는지 모르겠네요..

2021-07-09 08:33 UTC, brad-go commented
< update >
목표: 클릭하면 배경을 linear-gradient로 설정하기
1. app1.js - css파일을 자바스크립트에 가져와서 직접 작성
2. app2.js - css에서 변수를 만들어 자바스크립에서 그 변수에 접근한 후 변경하기
3. background에 접근해서 linear-gradient 설정하기 --> 정답이었다... 문법을 알지 못해 오래 헤맸다. ㅠ

2021-07-11 03:39 UTC, brad-go commented
< update >
목표 : todo-list 기능 추가하기

1. todo-list를 위한 form과 input 태그 추가
2. todo를 추가하고, 화면에 그리고, 로컬스토리지에 저장하고, 삭제하는 함수 추가
- handleToDoSubmit
- paintToDos
- saveToDos
- deleteToDo
3. JSON.stringify와 JSON.parse를 통해 local storage에 값을 문자열로 저장하거나 local storage에 있는 string을 JS에서 살아있는 object로 만들기
4. 배열의 요소들에게 각각 함수를 실행하는 forEach()와 filter() 사용

2021-07-11 08:22 UTC, brad-go commented
< UPDATE >
목표: 현재 위치와 날씨 정보를 알아내서 화면에 표시하기

1. 현재 위치를 얻는 함수 작성
- navigator.geolocation.getCurrentPosition()
2. 날씨 API사용
3. fetch() 사용

2021-07-11 17:13 UTC, brad-go commented
< UPDATE >

1. CSS를 통해 요소들 위치, 크기, 색상 등 조정
2. 모멘텀 앱과 비슷하게 로그인 시 시계와 투두리스트 작성 폼이 화면에 나타나게 설정

2021-07-12 07:39 UTC, WongueShin requested changes
API키 보안 관련해서 한 번 더 확인해주세요

2021-07-12 07:39 UTC, WongueShin commented on nativeJS/brad_Go/Momentum App_files/greeting.js
> +const USERNAME_KEY = "username";
코드 난독화를 방지하는 이런부분 상당히 좋은거 같습니다!

2021-07-12 07:39 UTC, WongueShin commented on nativeJS/brad_Go/Momentum App_files/todo.js
> +const toDoInput = toDoForm.querySelector("input");
form 안에 복수의 input이 있는 경우에는 3번 라인의 의미가 불분명하겠죠?
#id나 .classname으로 선택하는건 어떨까요?

2021-07-12 07:39 UTC, WongueShin commented on nativeJS/brad_Go/Momentum App_files/weather.js
> +const API_KEY = "58027f0571da8e29b2c21d20825de91d"
이렇게 API key가 깃허브 상에 올라오면 타인에 의한 남용, 악용이 될 수 있기 떄문에 절대로 올려서는 안됩니다!
가능한 빨리 현재 키를 삭제하고 재 발급 하시는게 좋을 거 같습니다

2021-07-12 07:39 UTC, WongueShin commented on nativeJS/brad_Go/momentum/js/weather.js
> +const API_KEY = "58027f0571da8e29b2c21d20825de91d"
이부분도 동일합니다! 수정이 필요해요

2021-07-12 09:02 UTC, brad-go commented on nativeJS/brad_Go/Momentum App_files/todo.js
> +const toDoInput = toDoForm.querySelector("input");
앗 다시보니 그러네요. 감사합니다!

2021-07-12 09:38 UTC, brad-go commented
API 수정완료 했습니다!

2021-07-13 09:28 UTC, merged