3주차시작
JavaScript101study/JsStudy pull request #49
Opened 2021-07-14 11:29 UTC by gustmd213

- 구글폰트 추가
- 디자인 수정
- 취소선 저장
- 처음 로그인시 기능 안되는 오류수정

2021-07-16 11:34 UTC, gustmd213 commented
저번 merge revert이후에 메인 브랜치와 momentum 브래치가 꼬여서 복구 함

2021-07-20 01:02 UTC, WongueShin requested changes
KEY 관련 보안부분 확인해주셔요!

2021-07-20 08:34 UTC, gustmd213 commented on nativeJS/gustmd213/momentum/js/config.js
> +const HIDDEN_CLASSNAME = "hidden";
저번 merge한거 revert하면서 예전버전이 올라가는 문제가 생긴것 같습니다.  수정하겠습니다.

2021-07-20 08:35 UTC, gustmd213 commented on nativeJS/gustmd213/momentum/js/config.js
> +    weatherApiKey: "e0e875c6e68c9590ad6b2cb0ea773fc6"
저번 merge한거 revert하면서 예전버전이 올라가는 문제가 생긴것 같습니다.  수정하겠습니다.

2021-07-20 08:36 UTC, gustmd213 commented on nativeJS/gustmd213/momentum/css/style.css
> +  display: none !important;
css 우선순위에서 클래스 선택자가 낮더라구요 그래서 숨겨지지 않는 이슈가 생겼어서 무조건 먼저 되도록 import를 지정해줬습니다.

2021-07-20 08:43 UTC, WongueShin commented on nativeJS/gustmd213/momentum/css/style.css
> +  display: none !important;
ㅋㅋㅋ 저도 비슷한 이슈가 있어서 같은 방식으로 해결하긴 했는데,
이런 방법은 별로 좋지 않은 방법임을 알고는 계셔야합니다!
예시를 들자면 goto문이 안좋은 이유하고 비슷하겠네요.
가끔 어쩔수 없이 써야할 때가 있을수도 있지만,  그 이전에 다른 해결책이 없는지 확인해보시는게 좋을거 같아요.

2021-07-20 08:53 UTC, merged